def A():
    print("        #        ")
    print("       # #       ")
    print("      #   #      ")
    print("     #     #     ")
    print("    #       #    ")
    print("   #         #   ")
    print("  #############  ")
    print(" #             # ")
    print("#               #")
A()