def B():
    print("   #######     ")
    print("   #      #    ")
    print("   #       #   ")
    print("   #      #    ")
    print("   #######     ")
    print("   #      #    ")
    print("   #       #   ")
    print("   #      #    ")
    print("   #######     ") 
B()